-- 코드를 입력하세요
SELECT P.PRODUCT_CODE , C.SALES FROM PRODUCT P JOIN
(SELECT P2.PRODUCT_ID, P2.PRICE * SUM(O2.SALES_AMOUNT) AS SALES FROM PRODUCT P2 
     JOIN OFFLINE_SALE O2
     ON P2.PRODUCT_ID = O2.PRODUCT_ID
    GROUP BY P2.PRODUCT_ID) C
ON P.PRODUCT_ID = C.PRODUCT_ID
ORDER BY C.SALES DESC , P.PRODUCT_CODE ASC;