            
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M LEFT JOIN REST_REVIEW R 
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_NAME = (SELECT M2.MEMBER_NAME 
                       FROM MEMBER_PROFILE M2
                       JOIN REST_REVIEW R2 ON M2.MEMBER_ID = R2.MEMBER_ID
                       GROUP BY M2.MEMBER_NAME
                       ORDER BY SUM(R2.REVIEW_SCORE) DESC
                       LIMIT 1)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;