-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(C.SUMS) AS TOTAL_SALES FROM BOOK B JOIN
 (SELECT BOOK_ID ,SUM(SALES) AS SUMS FROM BOOK_SALES 
 WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
 GROUP BY BOOK_ID) C 
ON B.BOOK_ID = C.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
